# Generated by Django 3.1.4 on 2020-12-13 06:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer_profile', '0001_initial'),
        ('seller_profile', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_extended', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserExtended',
            new_name='Extension',
        ),
    ]
