# Generated by Django 3.1.4 on 2020-12-13 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_extended', '0006_auto_20201213_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extension',
            name='city',
            field=models.CharField(default='qr', max_length=2),
        ),
    ]
