# Generated by Django 3.1.4 on 2020-12-11 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='image',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='user',
        ),
    ]
