# Generated by Django 3.1.4 on 2020-12-11 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller_profile', '0004_auto_20201211_1241'),
        ('apartment', '0002_auto_20201211_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='apartment',
            field=models.PositiveSmallIntegerField(default=None),
        ),
        migrations.AddField(
            model_name='apartment',
            name='home',
            field=models.PositiveSmallIntegerField(default=None),
        ),
        migrations.AddField(
            model_name='apartment',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='seller_profile.seller', verbose_name='Seller/Owner of apartment'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='street',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
