# Generated by Django 3.1.4 on 2020-12-13 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_extended', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_extended.userextended', verbose_name='Associated user')),
            ],
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(default=None, max_length=50)),
                ('home', models.PositiveSmallIntegerField(default=None)),
                ('apartment', models.PositiveSmallIntegerField(default=None)),
                ('owner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='seller_profile.seller', verbose_name='Seller/Owner of apartment')),
            ],
        ),
    ]
