# Generated by Django 3.1.4 on 2020-12-13 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_extended', '0003_auto_20201213_0712'),
        ('seller_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to='user_extended.extension', verbose_name='Associated user'),
        ),
    ]
