# Generated by Django 3.1.4 on 2020-12-11 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='image',
            field=models.ImageField(default='default_image/default.jpeg', upload_to='profile_image'),
        ),
    ]
