# Generated by Django 3.1.4 on 2020-12-11 12:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('seller_profile', '0002_auto_20201211_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='city',
            field=models.CharField(choices=[('qr', 'qarafandi'), ('as', 'astana'), ('al', 'almaty'), ('jz', 'jezqazfan'), ('mx', 'mvxosranskh')], default='qr', max_length=2),
        ),
        migrations.AlterField(
            model_name='seller',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
