# Generated by Django 3.1.4 on 2020-12-13 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller_profile', '0003_apartmentimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentimage',
            name='image',
            field=models.ImageField(default='default_image/apartment.jpeg', upload_to='apartment_images'),
        ),
    ]
