# Generated by Django 3.1.4 on 2020-12-11 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_extended', '0001_initial'),
        ('seller_profile', '0004_auto_20201211_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='city',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='image',
        ),
        migrations.AlterField(
            model_name='seller',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_extended.userextended', verbose_name='Associated user'),
        ),
    ]
