# Generated by Django 3.1.4 on 2020-12-11 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0003_auto_20201211_1310'),
        ('user_extended', '0001_initial'),
        ('buyer_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='apartment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apartment.apartment'),
        ),
        migrations.AddField(
            model_name='buyer',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_extended.userextended'),
        ),
    ]
